---

- name: Make sure Homebrew exists
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Download and install
  shell: bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when:
    - not homebrew_check.stat.exists

- name: Download Homebrew installation script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/install
  when:
    - not homebrew_check.stat.exists

- name: Install Homebrew
  shell: bash /tmp/install < /dev/null
  when:
    - not homebrew_check.stat.exists
