---

- name: Tap nightly cask
  homebrew_tap:
    name: jason0x43/homebrew-neovim-nightly

- name: Install neovim nightly
  homebrew_cask:
    name: neovim-nightly
    state: present

- name: Install vim-plug
  shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
